### ISSUE TITLE
[QUESTION:] noSaveAll Config

### ISSUE THREAD

**Issue by Masuary** [someaddons/smoothchunksave#3]
### Describe the bug you're experiencing

What do you mean with the "If you enable the noSaveAll config"

Do you mean the /save-off command to disable vanilla saving

### Reproducability

N/A

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.2

### Modloader version

Forge

### Logs

None

**Comment by someaddons** [comment]
oh it is to prevent a manual /save from being triggered, as some hosters do that automatically, doesnt exist anymore in newer versions, can just leave it at default
