### ISSUE TITLE
Permission for Modpack

### ISSUE THREAD

**Issue by AqueleHaru** [someaddons/smoothchunksave#6]
Hey there, can I include this mod in my modpack? "[Smooth Chunk Save](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)" I was planning on uploading to Modrinth. In order for that to happen, Modrinth needs authorization from Mod-Authors who do not give express consent, so basically those who have set "All Rights Reserved" as their License.

Of course i'll link the mod in description and the credits. thanks

**Comment by AqueleHaru** [comment]
Cupboard and farsight too.

**Comment by someaddons** [comment]
Hi,

Thanks for wanting to include my mods in your modpack. I distribute my mods exclusively on CurseForge, so I only allow them to be included in modpacks hosted on that platform. If your modpack is on CurseForge, feel free to include my mods.

Best regards,

Sam
