### ISSUE TITLE
[Bug]: Game crashes randomly when loading / saving chunks

### ISSUE THREAD

**Issue by team1257Simon** [someaddons/smoothchunksave#7]
### Describe the bug you're experiencing

The crash occurs normally either when I generate a chunk or when I teleport home and thus reload those chunks.

### Reproducability

Travel into an ungenerated chunk or leave one that was recently generated.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.21.1

### Modloader version

Forge

### Logs

https://gist.github.com/team1257Simon/629855e07ea4ca8bb625b570f77ecd51

**Comment by someaddons** [comment]
The log you have attached is about entities when loading a chunk, meanwhile this mod is about saving chunks to disk in intervals so I dont really see how it is connected. Generating new chunks work just fine for me
